config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  #--Session Routes--#
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  delete '/logout', to: 'sessions#destroy', as: 'delete_user_session'

  #--Users Routes--#
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  

  #--Logs Routes--#
  resources :users, only: [] do
    resources :logs
  end
  
  resources :logs

  get '/longest_log', to: 'logs#long_log'
  
  #--Routes Routes--#
  resources :routes
 
  #--Comment Routes--#
  resources :logs, only: [] do 
    resources :comments
  end 




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end 
end 

app/views/home/index.html.erb
<h1 class="main">Welcome to your climbing log!</h1>

<h3><br> Create an account and start logging your climbs today! <br><br> Track your logs! <br> See other people's climbs! <br> Leave comments on other people's logs!
<br><br> </h3>


<%= link_to :log_page, user_log_path(@user) if @user %>

<% unless current_user %>
  <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
<% else %>
  <%= link_to "Logout", delete_user_session_path, method: :delete %>
<% end %>



<%= link_to :signup, signup_path if !@user %>

<%= link_to :login, login_path if !@user %>