config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  #--Session Routes--#
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  delete '/logout', to: 'sessions#destroy', as: 'delete_user_session'

  #--Users Routes--#
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  

  #--Logs Routes--#
  resources :users, only: [] do
    resources :logs
  end
  
  resources :logs

  get '/longest_log', to: 'logs#long_log'
  
  #--Routes Routes--#
  resources :routes
 
  #--Comment Routes--#
  resources :logs, only: [] do 
    resources :comments
  end 




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
    has_many :logs
    has_many :comments, through: :logs
    

    

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_log
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.grade(params[:grade])

  end

  def create 
    @route = @log.route.build(route_params)
  end

  def show
    
    @route = Route.find_by_id(params["id"])
  end 

  
   
 




  private
      
      def route_params
        params.require(:route).permit(:name, :location, :grade)
      end 

end

app/helpers/route_helper.rb
module RouteHelper
end

app/views/routes/_form.html.erb
<%= form_for [@user, route] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>

    <%= f.label :location %>
    <%= f.text_field :location, required: true %>

    <%= f.label :grade %>
    <%= f.text_field :grade, required: true %>

    <%= f.submit button_name, class: "btn" %>
<% end %>

app/views/routes/edit.html.erb
  
<h1>Edit Climbs</h1>
<%= render partial: "form", locals: { route: @route, button_name: "Edit Route" } %>

app/views/routes/index.html.erb
<h1 class="log">Search for routes!</h1>
<h3 class="log"><%= form_tag routes_path, method: "get" do %>
    <%= text_field_tag :grade %>
    <%= submit_tag :search %>
<% end %>
</h3>

            

app/views/routes/new.html.erb
<h1>Add Route!</h1>
<%= render partial: "form", locals: {route: @route, button_name: "Add Route"} %>

app/views/routes/show.html.erb
<h1 class="log">Routes Page!</h1>

<h3 class="log"><br><%= @route.name %>  has the following logs:
 
 <% @route.logs.each do |l| %>
  <%= link_to l.log_date, log_path(l.id) %>
<% end %>
<br><br>
</h3>