config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  #--Session Routes--#
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  delete '/logout', to: 'sessions#destroy', as: 'delete_user_session'

  #--Users Routes--#
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  

  #--Logs Routes--#
  resources :users, only: [] do
    resources :logs
  end
  
  resources :logs

  get '/longest_log', to: 'logs#long_log'
  
  #--Routes Routes--#
  resources :routes
 
  #--Comment Routes--#
  resources :logs, only: [] do 
    resources :comments
  end 




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/log.rb
class Log < ApplicationRecord
    belongs_to :user
    has_one :route
    has_many :comments, dependent: :destroy 

    scope :search, -> (query, user) { query ? user.logs.where("log_date LIKE ?", "%#{query}%") : user.logs }

    scope :longest_log, -> {where(log: "longest_log")}
    # accepts_nested_attributes_for :route

    def route_attributes=(route_attributes)
        @route = Route.find_or_create_by(route_attributes)
        self[:route_id] = @route.id
    end 

    def comment_attributes=(comment_attributes)
            @comment = Comment.create(comment_attributes)
            self.comments << @comment

    end 

    def self.longest_log
        longest_log_element = ""
        Log.all.each do |l|
            if l.log_date.length > longest_log_element.length
                longest_log_element = l.log_date
            end 
        end 
        longest_log_element
    end 

    def log_id 
        self.id
    end 
 
    
    def route
        Route.find_by_id(self.route_id)
    end

    
end

app/controllers/log_controller.rb
class LogController < ApplicationController
  def new
  end

  def show
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_user
  before_action :set_log, only: [:show, :edit, :update, :destroy]
   
  def index
    @logs = Log.search(params[:query], @user)
  end

  def new
    @log = Log.new
    @route = Route.new

  end 

  def long_log
    @logs = Log.where(params[:longest_log])
  end 


  def create
    @log = @user.logs.create(log_params)
    if @log.save
        redirect_to user_logs_path
    else 
        render :new
    end
  end 

  def destroy 
    @log.destroy
    redirect_to user_logs_path
  end 

  def edit
    redirect_to user_logs_path unless current_user == @user
  end 

def update
    if @log.update(log_params)
        redirect_to user_logs_path
    else
        render :edit
    end 
end 

private 

  def log_params
    params.require(:log).permit(:log_date, :content, :num_of_attempts, :user_id, :route_id, route_attributes: [:name, :location, :grade])
  end 

  def set_log
    @log = Log.find_by_id(params[:id])
  end

  



  
end

app/helpers/log_helper.rb
module LogHelper
end

app/views/logs/_form.html.erb
<h3 class="log"><%= form_for [@user, log] do |f| %>
<p>
  <%= f.label :log_date %><br>
  <%= f.text_field :log_date %>
 </p>
 <p>
  <%= f.label :log %><br>
  <%= f.text_area :content %>
 </p>
 <p>
  <%= f.label :number_of_attemps %><br>
  <%= f.text_field :num_of_attempts %>
 </p>


 <p>
  <%=f.fields_for :route, log.build_route do |route_fields| %>
    <p>
    <%= f.label :name %><br>
    <%= route_fields.text_field :name %>
    </p>
 <p>
    <%= f.label :location %><br>
    <%= route_fields.text_field :location %>
    </p>
 <p>
    <%= f.label :grade %><br>
    <%= route_fields.text_field :grade%>
    </p>
  <% end %>



    <%= f.submit button_name, class: "btn" %>
<% end %>
</h3>

app/views/logs/edit.html.erb
<h1 class="log">Edit Log</h1>
<%= render partial: "form", locals: { log: @log, button_name: "Edit Log" } %>

app/views/logs/index.html.erb
<h1 class="log">Climbs</h1>

<h3 class="log"><br>Searh for logs!<%= form_tag user_logs_path(@user), method: "get" do %>
    <%= text_field_tag :query %>
    <%= submit_tag :search %>
<% end %><br>
</h3>







<h3 class="log"><div class="card"><div class="container"> <br><a href=logs/new>Add a climb log!</a>


         <table class="center">
        <thead>
          <tr>
              <th>Name</th>
              <th>View</th>
              <th>Edit</th>
              <th>Delete</th>
          </tr>
        </thead>

        <tbody>
            <% if current_user == @user %>
                <% @logs.each do |r| %>
                    <tr>
                        <td><%= r.log_date %></td>
                        <td><%= link_to "View", user_log_path(@user, r) %></td>
                        <td><%= link_to "Edit", edit_user_log_path(@user, r) %></td>
                        <td><%= link_to "Delete", user_log_path(@user, r), method: "delete" %></td>
                    </tr>
                <% end %>
            <% end %>
        </tbody>
    </table>
    </div></div>
    </h3>

        
            
<%= link_to "Log out", delete_user_session_path, method: :delete %>

app/views/logs/long_log.html.erb
<%= Log.longest_log %>

app/views/logs/new.html.erb
<h1 class="log">Add Log!</h1>
<%= render partial: "form", locals: {log: @log, button_name: "Add Log"} %>

app/views/logs/show.html.erb
<h1 class="log">Log Page</h1>
<h3><br><div class="card"><div class="container"> Route: <%= link_to @log.route.name, route_path(@log.route) if @log.route %>
<%= @log.route.grade %> <%=  @log.route.location %>
<br><br><%= @log.log_date %><p class="details"><%= @log.content %></p><br></div></div> Comments:
  <% @log.comments.each do |c| %>
   <div class="card"><div class="container">
 <p class="comments"><%= c.content %></p></div></div>
  <% end %></h3>


 






<h1 class="comments">Leave a reply!</h1>
<%= render partial: "comments/form", locals: {comment: @comment, button_name: "reply"} %>